finchcollector/finchcollector/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls'))
]

finchcollector/main_app/urls.py
from django.urls import path
from . import views


urlpatterns = [
    # path(url_pattern, function, name)
    path('', views.home, name='home'),
    path('about/', views.about, name='about'),
    path('finches/', views.finches_index, name='index'),
    path('finches/<int:finch_id>/', views.finches_detail, name='detail' ),
    path('finches/create/', views.FinchCreate.as_view(), name='finches_create' ),
    path('finches/<int:pk>/update/', views.FinchUpdate.as_view(), name='finches_update'),
    path('finches/<int:pk>/delete/', views.FinchDelete.as_view(), name='finches_delete'),
    path('toys/', views.ToyList.as_view(), name='toys_list'),
    path('toys/<int:pk>/', views.ToyDetail.as_view(), name='toys_detail'),
    path('toys/create/', views.ToyCreate.as_view(), name='toys_create'),
    path('toys/<int:pk>/update/', views.ToyUpdate.as_view(), name='toys_update'),
    path('toys/<int:pk>/delete/', views.ToyDelete.as_view(), name='toys_delete'),
    path('finches/<int:finch_id>/add_feeding/', views.add_feeding, name='add_feeding'),
    path('finches/<int:finch_id>/assoc_toy/<int:toy_id>/', views.assoc_toy, name='assoc_toy'),
    path('finches/<int:finch_id>/unassoc_toy/<int:toy_id>/', views.unassoc_toy, name='unassoc_toy'),
]

finchcollector/main_app/models.py
from django.db import models
from django.urls import reverse


# Create your models here.
class Toy(models.Model):
    name = models.CharField(max_length=50)
    color = models.CharField(max_length=50)

    def __str__(self):
        return f'A {self.color} {self.name}'
    
    def get_absolute_url(self):
        return reverse('toys_detail', kwargs={'pk': self.id})

class Finch(models.Model):
    name = models.CharField(max_length=100)
    home = models.CharField(max_length=100)
    description = models.TextField(max_length=250)
    fact = models.TextField()
    toys = models.ManyToManyField(Toy)
    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse("detail", kwargs={"finch_id": self.id})
    
class Feeding(models.Model):
    MEALS = (
        ('B', 'Breakfast'),
        ('L', 'Lunch'),
        ('D', 'Dinner')
    )
    date = models.DateField('feeding date')
    meal = models.CharField(
        max_length=1,
        # add the 'choices' field option
        choices=MEALS,
        # set the default value for meal to be 'B'
        default=MEALS[0][0]
    )
    finch = models.ForeignKey(Finch, on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.get_meal_display()} on {self.date}'
    
    
    class Meta:
        ordering = ['-date']

finchcollector/main_app/forms.py
from django.forms import ModelForm
from .models import Feeding

class FeedingForm(ModelForm):
    class Meta:
        model = Feeding
        fields = ['date', 'meal']

finchcollector/main_app/views.py
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic import ListView, DetailView
from django.shortcuts import render
from .models import Finch, Toy
from django.shortcuts import render, redirect
from .models import Finch
from .forms import FeedingForm


# Create your views here.
def home(request):
    # Include an .html file extension - unlike when rendering EJS templates
    return render(request, 'home.html')

def about(request):
    return render(request, 'about.html')

def finches_index(request):
    finches = Finch.objects.all()
    return render(request, 'finches/index.html', {
    'finches': finches
})
    
def finches_detail(request, finch_id):
    finch = Finch.objects.get(id=finch_id)
    id_list = finch.toys.all().values_list('id') # [1, 3, 7]

    toys_finch_doesnt_have = Toy.objects.exclude(id__in=id_list)

    feeding_form = FeedingForm()
    return render(request, 'finches/detail.html', 
    { 
        'finch': finch,
        'feeding_form': feeding_form,
        'toys': toys_finch_doesnt_have
    })
def add_feeding(request, finch_id):
    form = FeedingForm(request.POST)

    # validate the form
    if form.is_valid():
        new_feeding = form.save(commit=False)
        new_feeding.finch_id = finch_id
        '''
        {
            meal: 'B',
            date: '2023-06-02',
            cat_id: 1
        }
        '''
        new_feeding.save()
    return redirect('detail', finch_id=finch_id)

def assoc_toy(request, finch_id, toy_id):
    Finch.objects.get(id=finch_id).toys.add(toy_id)
    return redirect('detail', finch_id=finch_id)

def unassoc_toy(request, finch_id, toy_id):
    Finch.objects.get(id=finch_id).toys.remove(toy_id)
    return redirect('detail', finch_id=finch_id)
class FinchCreate(CreateView):
    model = Finch
    fields = ['name', 'home', 'description', 'fact']
    # success_url = '/finches/' # not the preferred way 
    
class FinchUpdate(UpdateView):
    model = Finch
    fields = ['description', 'fact']
    
class FinchDelete(DeleteView):
    model = Finch
    success_url = '/finches/'
    
class ToyCreate(CreateView):
    model = Toy
    fields = ['name', 'color']

class ToyList(ListView):
    model = Toy

class ToyDetail(DetailView):
    model = Toy

class ToyUpdate(UpdateView):
    model = Toy
    fields = ['name', 'color']

class ToyDelete(DeleteView):
    model = Toy
    success_url = '/toys/'

finchcollector/main_app/templates/about.html
{% extends 'base.html' %}
{% block content %}

<h1>About the Finch Collector</h1>
<hr>
<p>Hire the Finch Collector!</p>
<footer>All Rights Reserved, &copy; 2023 Finch Collector</footer>

{% endblock %}

finchcollector/main_app/templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>Finch Collector</title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
        <link rel="stylesheet" type="text/css" href="{% static 'parallax-template/css/style.css' %}">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
    </head>
    <body>  
        <header class="navbar-fixed">
            <nav>
              <div class="nav-wrapper">
                <ul>
                  <li><a href="{% url 'home' %}" class="left brand-logo">&nbsp;&nbsp;Finch Collector</a></li>
                </ul>
                <ul class="right">
                  <li><a href="{% url 'about' %}">About</a></li>
                  <li><a href="{% url 'finches_create'%}"> Add a Finch</a></li>
                  <li><a href="{% url 'index'%}">View All My Finches</a></li>
                  <li><a href="{% url 'toys_list' %}">View All Toys</a></li>
                  <li><a href="{% url 'toys_create' %}">Add a Toy</a></li>
                </ul>
              </div>
            </nav>
          </header>
          <main class="container">
            {% block content %}
            {% endblock %}
          </main>
          <footer class="page-footer">
            <div class="right">All Rights Reserved, &copy; 2021 Finch Collector &nbsp;</div>
          </footer>
    </body>
</html>

finchcollector/main_app/templates/finches/detail.html
{% extends 'base.html' %}

{% block content %}
<div class="card">
    <div class="card-content">
      <span class="card-title">{{ finch.name }}</span>
      <p>Breed: {{ finch.home }}</p>
      <p>Description: {{ finch.description }}</p>
      <p>Fun Fact: {{ finch.fact }}</p>
      
    </div>
    <div class="card-action">
        <a href="{% url 'finches_update' finch.id %}">Edit</a>
        <a href="{% url 'finches_delete' finch.id %}">Delete</a>
    </div>
  </div>

  <div class="col s6">
    {% if feeding.date == date.today %}

    <div>
      <h3>Fed!</h3>
    </div>
    {% else %}
    <div>
      <h3>Hungry!</h3>
    </div>
    {% endif %}
    <form action="{% url 'add_feeding' finch.id %}" method="POST">
        {% csrf_token %}
        <!-- Render the inputs -->
        {{ feeding_form.as_p }}
        <input type="submit" class="btn" value="Add Feeding">
    </form>
    <table class="striped">
      <thead>
        <tr><th>Date</th><th>Meal</th></tr>
      </thead>
      <tbody>
        {% for feeding in finch.feeding_set.all %}
          <tr>
            <td>{{feeding.date}}</td>
            <td>{{feeding.get_meal_display}}</td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
  <!-- New Markup Above -->
</div>

<hr> <!-- Horizontal Rule Tag -->

<div class="row">
  <div class="col s6">
    <h3>{{ finch.name }}'s Toys</h3>
    {% if finch.toys.count %}
      {% for toy in finch.toys.all %}
        <div class="card">
          <div class="card-content">
            <span class="card-title">
              A <span class="{{ toy.color.lower }}-text">{{ toy.color }}</span> {{ toy.name }}
            </span>
          </div>
          <div class="card-action">
            <form action="{% url 'unassoc_toy' finch.id toy.id %}" method="post">
              {% csrf_token %}
              <input type="submit" value="Remove" class="btn red">
            </form>
          </div>
        </div>
      {% endfor %}
    {% else %}
      <h5>{{finch.name}} doesn't have any toys 🦜</h5>
    {% endif %}
  </div>
  <div class="col s6">
    <h3>Available Toys</h3>
    {% if toys.count %}
      {% for toy in toys %}
      <div class="card">
        <div class="card-content">
          <span class="card-title">
            A <span class="{{ toy.color.lower }}-text">{{ toy.color }}</span> {{ toy.name }}
          </span>
        </div>
        <div class="card-action">
          <form action="{% url 'assoc_toy' finch.id toy.id %}" method="post">
            {% csrf_token %}
            <input type="submit" value="Add" class="btn blue">
          </form>
        </div>
      </div>
      {% endfor %}
    {% else %}
    <h5>{{ finch.name }} Already Has All Toys Available</h5>
    {% endif %}
  </div>
</div>



<!-- below all HTML -->
<script>
  const dateEl = document.getElementById('id_date');
  // M is Materialize's global variable
  M.Datepicker.init(dateEl, {
    format: 'yyyy-mm-dd',
    defaultDate: new Date(),
    setDefaultDate: true,
    autoClose: true
  });

  const selectEl = document.getElementById('id_meal');
  M.FormSelect.init(selectEl)
</script>


{% endblock %} 

finchcollector/main_app/templates/finches/index.html
{% extends 'base.html' %}
{% block content %}

<h1>Finch List</h1>

{% for finch in finches %}
<a href="{% url 'detail' finch.id %}">
  <div class="card">
    <div class="card-content">
        <span class="card-title">{{ finch.name }}</span>
        <p>Home: {{ finch.home }}</p>
        <p>Description: {{ finch.description }}</p>
        <p>Fact: {{ finch.fact }}</p>
    </div>
  </div>
  </a>
{% endfor %}

{% endblock %}

finchcollector/main_app/templates/home.html
{% extends 'base.html' %}
{% block content %}

<h1>Welcome to the Finch Collector's Home Page</h1>
<hr>
<p>The Finches Nest!</p>
<div class="card">
    <div class="card-content">
    <img src="../static/imgs/pic1.jpg" alt=""> 
    <img src="../static/imgs/pic2.jpg" alt=""> 
    <img src="../static/imgs/pic3.jpg" alt=""> 

    </div> 
</div>
<footer>All Rights Reserved, &copy; 2023 Finch Collector</footer>

{% endblock %}

finchcollector/main_app/templates/main_app/finch_confirm_delete.html
{% extends 'base.html'%}

{% block content %}

<h3>Are you sure you want to delete{{ object.name }}</h3>

<form action="" method="post">
    {% csrf_token %}
    <input class="btn red" type="submit" value="Yes - Delete">
    <a class="btn blue" href="{% url 'detail' object.id %}">No - Cancel</a>
</form>

{% endblock %}

finchcollector/main_app/templates/main_app/finch_form.html
{% extends 'base.html' %}

{% block content %}
{% if object %}
<h1>Edit Finch</h1>
{% else %}
<h1>Add Finch</h1>
{% endif %}

<form action="" method="post">
    {% csrf_token %}
    <table>
        {{ form.as_table }}
    </table>
    <input class='btn blue' type='submit' value='{% if object %} Edit Finch {% else %} Add Finch {% endif %}'>
</form>


{% endblock %}

finchcollector/main_app/templates/main_app/toy_confirm_delete.html
{% extends 'base.html' %}

{% block content %}

<h3>Are you sure you want to delete the <span style=color: {{ object.color.lower }}>{{ object.color }}</span> {{ object.name }}?</h3>

<form action="" method="post">
    {% csrf_token %}
    <input class="btn red" type="submit" value="Yes - Delete">
    <a class="btn blue" href="{% url 'toys_detail' object.id %}">No - Cancel</a>
</form>

{% endblock %}

finchcollector/main_app/templates/main_app/toy_detail.html
   
{% extends 'base.html' %}

{% block content %}

<h1>Toy Detail</h1>

<div class="card">
    <div class="card-content">
      <span class="card-title">A <span style="color: {{ object.color.lower }}">{{ object.color }}</span> {{ object.name }}</span>
    </div>
    <div class="card-action">
      <a href="{% url 'toys_update' object.id %}">Edit</a>
      <a href="{% url 'toys_delete' object.id %}">Delete</a>
    </div>
  </div>
</div>

{% endblock %}

finchcollector/main_app/templates/main_app/toy_form.html
{% extends 'base.html' %}

{% block content %}

{% if object %}
    <h1>Edit Toy</h1>
{% else %}
    <h1>Add Toy</h1>
{% endif %}

<form action="" method="post">
    {% csrf_token %}
    <table>
        {{ form.as_table }}
    </table>
    <input class="btn blue" type="submit" value="{% if object %} Update Toy {% else %} Add Toy {% endif %}">
</form>

{% endblock %}

finchcollector/main_app/templates/main_app/toy_list.html
{% extends 'base.html' %}

{% block content %}

<h1>Toy Index</h1>

{% for toy in object_list %}

<a href="{% url 'toys_detail' toy.id %}">
    <div class="card">
        <div class="card-content">
            <span class="card-title">A <span style="color: {{ toy.color.lower }}">{{ toy.color }}</span> {{ toy.name }}</span>
        </div>
    </div>
</a>

{% endfor %}

{% endblock %}